<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jordan Dever">

<title>Midterm Programming</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Midterm_Jordan_Dever_files/libs/clipboard/clipboard.min.js"></script>
<script src="Midterm_Jordan_Dever_files/libs/quarto-html/quarto.js"></script>
<script src="Midterm_Jordan_Dever_files/libs/quarto-html/popper.min.js"></script>
<script src="Midterm_Jordan_Dever_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Midterm_Jordan_Dever_files/libs/quarto-html/anchor.min.js"></script>
<link href="Midterm_Jordan_Dever_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Midterm_Jordan_Dever_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Midterm_Jordan_Dever_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Midterm_Jordan_Dever_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Midterm_Jordan_Dever_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Midterm Programming</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Jordan Dever </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DescTools); <span class="fu">library</span>(MASS)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(BSDA)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: lattice</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'BSDA'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:datasets':

    Orange</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'carData'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:BSDA':

    Vocab, Wool</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'car'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:DescTools':

    Recode</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tinytex)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"C:/Users/jorda/OneDrive/Documents/R-Studio/STA6443/HW"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="exercise-1" class="level1">
<h1>Exercise 1:</h1>
<section id="a" class="level3">
<h3 class="anchored" data-anchor-id="a">a)</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>bw <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">'birthweight.csv'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(bw<span class="sc">$</span>Weight)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Midterm_Jordan_Dever_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>For the boxplot on infant birth weight, it looks like it may follow the normal because the interquartile range looks about equal distant and the first and fourth quartiles are not skewed. There are four outliers, one to the right and three to the left that will influence the mean of the distribution.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(bw<span class="sc">$</span>Weight);<span class="fu">qqline</span>(bw<span class="sc">$</span>Weight)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Midterm_Jordan_Dever_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>For the QQ-plot, it looks like infant birth weight follows a normal distribution because almost all of the data points are along the line with the exception of 3 outliers near the bottom.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(bw<span class="sc">$</span>Weight)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  bw$Weight
W = 0.99206, p-value = 0.1153</code></pre>
</div>
</div>
<p>H0 = Follows a normal distribution<br>
HA = Does not follow a normal distribution.<br>
</p>
<p>Based on the Shapiro-Wilk test, we will fail to reject the null because our p = 0.1153 which is greater than our alpha level of &gt;0.05. We can state that for this data, birth weight in infants follows a normal distribution and is a reasonable assumption.</p>
</section>
<section id="b" class="level3">
<h3 class="anchored" data-anchor-id="b">b)</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(Weight <span class="sc">~</span> MomSmoke, <span class="at">data =</span> bw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Midterm_Jordan_Dever_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Looking at the two boxplots, in the non-smoking mom group it looks like the data follows a normal distribution and has a wider spread of data being ~2250 to ~4750g. The smoking mom group looks to be right skewed within the interquartile but the 1st and 4th quartiles look equidistant so it could be normally distributed. The smoking mom group also has less spread being at ~2500 to ~4000 and does not reach weights higher than 4000. Both groups have outliers, but the non-smoking group has the only positive outlier.</p>
</section>
<section id="c" class="level3">
<h3 class="anchored" data-anchor-id="c">c)</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(bw<span class="sc">$</span>Weight [bw<span class="sc">$</span>MomSmoke<span class="sc">==</span><span class="dv">0</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  bw$Weight[bw$MomSmoke == 0]
W = 0.99362, p-value = 0.3549</code></pre>
</div>
</div>
<p>Mom Doesn’t Smoke p = 0.3549</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(bw<span class="sc">$</span>Weight [bw<span class="sc">$</span>MomSmoke<span class="sc">==</span><span class="dv">1</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  bw$Weight[bw$MomSmoke == 1]
W = 0.96299, p-value = 0.2</code></pre>
</div>
</div>
<p>Mom Smokes p = 0.2</p>
<p>Based on the p-values from the Shapiro-Wilk test (pNonSmoking = 0.3549, pSmoking = 0.2 &gt; 0.05), we must fail to reject the null hypothesis for the non-smoking and smoking mom groups for the infant weight distributions. Both groups follow a normal distribution.</p>
</section>
</section>
<section id="exercise-2" class="level1">
<h1>Exercise 2</h1>
<p>Since the birth weights of non-smoking and smoking are normally distributed, we can use a two-sample t-test (parametric). First we must test for equal variance to determine if we will use a pooled or Satterthwaite t-test.</p>
<p>t-test Hypothesis:<br>
H0: meanNonSmokingBW = meanSmokingBW | both means are equal to each other<br>
HA: meanNonSmokingBW != meanSmokingBW| the means are not equal<br>
</p>
<p>f-test hypothesis H0:<br>
varianceNonSmokingBW = varianceSmokingBW | both have equal variance<br>
HA: varianceNonSmokingBW != varianceSmokingBW | unequal variance between groups<br>
</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">var.test</span>(bw<span class="sc">$</span>Weight [bw<span class="sc">$</span>MomSmoke<span class="sc">==</span><span class="dv">0</span>], bw<span class="sc">$</span>Weight [bw<span class="sc">$</span>MomSmoke<span class="sc">==</span><span class="dv">1</span>], <span class="at">alternative =</span> <span class="st">'two.sided'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    F test to compare two variances

data:  bw$Weight[bw$MomSmoke == 0] and bw$Weight[bw$MomSmoke == 1]
F = 1.0786, num df = 253, denom df = 40, p-value = 0.8009
alternative hypothesis: true ratio of variances is not equal to 1
95 percent confidence interval:
 0.6421109 1.6671729
sample estimates:
ratio of variances 
          1.078555 </code></pre>
</div>
</div>
<p>F = 1.0786 p-value = 0.8009<br>
Since p = 0.8009 &gt; 0.05, we will fail to reject the null and state that both groups have equal variance. We can use a pooled t-test because of equal variance.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(bw<span class="sc">$</span>Weight [bw<span class="sc">$</span>MomSmoke<span class="sc">==</span><span class="dv">0</span>], bw<span class="sc">$</span>Weight [bw<span class="sc">$</span>MomSmoke<span class="sc">==</span><span class="dv">1</span>],</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">alternative =</span> <span class="st">'two.sided'</span>, <span class="at">var.equal =</span> T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  bw$Weight[bw$MomSmoke == 0] and bw$Weight[bw$MomSmoke == 1]
t = 3.071, df = 293, p-value = 0.002334
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
  93.37931 426.65488
sample estimates:
mean of x mean of y 
 3422.724  3162.707 </code></pre>
</div>
</div>
<p>t = 3.071 p-value = 0.002334<br>
mean of x mean of y 3422.724 3162.707<br>
The pooled t-test gave us a p-value of 0.002334 which is less than our alpha level of 0.05. We will reject the null and state that the non-smoking and smoking body weight means are significantly different from each other. This can be see in our t-test where the non-smoking mean is 3422.724 grams and the smoking mean is 3162.707 grams.</p>
</section>
<section id="exercise-3" class="level1">
<h1>Exercise 3</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>bw<span class="sc">$</span>MomSmoke <span class="ot">=</span> <span class="fu">as.factor</span>(bw<span class="sc">$</span>MomSmoke)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>aov.bw <span class="ot">=</span><span class="fu">aov</span>(Weight <span class="sc">~</span> MomSmoke, <span class="at">data =</span> bw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="a-1" class="level3">
<h3 class="anchored" data-anchor-id="a-1">a)</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">LeveneTest</span>(aov.bw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = median)
       Df F value Pr(&gt;F)
group   1  0.6767 0.4114
      293               </code></pre>
</div>
</div>
<p>p = 0.4114<br>
Since Levene’s test p-value is 0.4114 &gt; 0.05, we will fail to reject the null so it is ok to hold on our homogeneity of variance assumption and perform the ANOVA.</p>
</section>
<section id="b-1" class="level3">
<h3 class="anchored" data-anchor-id="b-1">b)</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(aov.bw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Df   Sum Sq Mean Sq F value  Pr(&gt;F)   
MomSmoke      1  2386708 2386708   9.431 0.00233 **
Residuals   293 74151291  253076                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Based on our p-value of 0.00233 (same as our t-test), we will reject the null and state that there are different mean body weights between the non-smoking and smoking mothers. The ANOVA does not show us a direct comparison of the mean values, only that one group is significantly different than the other. We got the same results from the pooled t-test.</p>
</section>
</section>
<section id="exercise-4" class="level1">
<h1>Exercise 4</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>bw<span class="sc">$</span>Black <span class="ot">=</span> <span class="fu">as.factor</span>(bw<span class="sc">$</span>Black)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>bw<span class="sc">$</span>Married <span class="ot">=</span> <span class="fu">as.factor</span>(bw<span class="sc">$</span>Married)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>bw<span class="sc">$</span>Boy <span class="ot">=</span> <span class="fu">as.factor</span>(bw<span class="sc">$</span>Boy)</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>bw<span class="sc">$</span>Ed <span class="ot">=</span> <span class="fu">as.factor</span>(bw<span class="sc">$</span>Ed)</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>aov.bw2 <span class="ot">=</span> <span class="fu">aov</span>(Weight <span class="sc">~</span> Black <span class="sc">+</span> MomSmoke, <span class="at">data =</span> bw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="a-2" class="level3">
<h3 class="anchored" data-anchor-id="a-2">a)</h3>
<p>For the backward selection, we will eliminate the least insignificant variable based on p-value (closest to 1.0) until we reach our stopping rule of being unable to eliminate a significant variable. Once a variable is eliminated it can not come back.</p>
<p>Step 1:<br>
Ed 7295 1 0.0300 0.8625846<br>
Education level is eliminated because it had a p-value of 0.8625846. Deleting ‘+Ed’ from aov.bw2</p>
<p>Step 2:<br>
Married 61146 1 0.2524 0.6157671<br>
Married is eliminated because it had the highest p-value. Deleting ‘+Married’ from aov.bw2</p>
<p>Step 3:<br>
Boy 179990 1 0.7449 0.3888071<br>
Boy is now the least significant variable. Deleting ‘+ Boy’ from aov.bw2</p>
<p>Step 4:<br>
MomSmoke 2513301 1 10.411 0.0013954 **<br>
MomSmoke is now the least significant variable, but since it is significant we have reached our stopping rule and can use the remaining variables for our final model (MomSmoke and Black)</p>
<p>Step 5: Check Interaction Effects<br>
Black:MomSmoke 5461 1 0.0225 0.8807474<br>
Since the interaction is not significant, I will omit it from the final model. Deleting ‘+Black*MomSmoke’.</p>
</section>
<section id="b-2" class="level3">
<h3 class="anchored" data-anchor-id="b-2">b)</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co">#final model</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>aov.bw3 <span class="ot">=</span> <span class="fu">aov</span>(Weight <span class="sc">~</span> Black <span class="sc">+</span> MomSmoke, <span class="at">data =</span> bw)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>t3.bw3 <span class="ot">=</span> <span class="fu">Anova</span>(aov.bw3, <span class="at">type=</span><span class="dv">3</span>)</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>t3.bw3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Anova Table (Type III tests)

Response: Weight
                Sum Sq  Df   F value    Pr(&gt;F)    
(Intercept) 2600800716   1 10772.989 &lt; 2.2e-16 ***
Black          3657042   1    15.148 0.0001232 ***
MomSmoke       2513301   1    10.411 0.0013954 ** 
Residuals     70494249 292                        
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Black 3657042 1 15.148 0.0001232 * <strong>MomSmoke 2513301 1 10.411 0.0013954</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>lm.bw3 <span class="ot">=</span> <span class="fu">lm</span>(Weight <span class="sc">~</span> Black <span class="sc">+</span> MomSmoke, <span class="at">data =</span> bw)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm.bw3)<span class="sc">$</span>r.squared</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.07896405</code></pre>
</div>
</div>
<p>r squared = 0.07896405 (7.9%)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(aov.bw3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Midterm_Jordan_Dever_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Our final model includes the main effects of race and smoking. Both main effects in our model were significant (pRace = 0.0001232 and pSmoke = 0.0013954) with the interaction effect not being significant (pRace*Smoke = 0.8807474) so it was removed from the final model. Since both main effects were significant, we must reject the null hypothesis then state that at least one race has a different mean body weight AND at least one smoking group has a different mean body weight. To see the differences between groups, we must run a post-hoc test. The interaction effect was not significant so we will fail to reject the null and state that there is no interaction effect for this model. Our amount of explainable variation for this model is ~7.9% (r squared = 0.07896405). We can also hold our assumption for normality based on the QQ-residuals following an almost straight line.</p>
</section>
<section id="c-1" class="level3">
<h3 class="anchored" data-anchor-id="c-1">c)</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(aov.bw3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = Weight ~ Black + MomSmoke, data = bw)

$Black
         diff       lwr       upr     p adj
1-0 -293.9412 -445.2216 -142.6608 0.0001605

$MomSmoke
        diff       lwr       upr     p adj
1-0 -266.763 -429.5199 -104.0061 0.0013989</code></pre>
</div>
</div>
<p>Black = 1 White = 0 | Smokes = 1 NonSmoke = 0<br>
</p>
<p>After doing Tukey’s post-hoc analysis test, we can see that white mothers have babies that weigh significantly more than babies from black mothers (p = 0.0001605, diff = -293.9412). We can also see that mothers that do not smoke produce babies that weigh significantly more than mothers that smoke (p = 0.0013989, diff = -266.763). White mothers give birth to babies that weigh more and are expected to be ~294 grams heavier than babies from black mothers with a p-value less than 0.05. Non-smoking mothers give birth to babies that weigh significantly more than smoking mothers and the babies are expected to be ~267 grams heavier with a p-value of less than 0.05.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>